//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlygodknows.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class access_date
    {
        public int Id { get; set; }
        public Nullable<int> emp_no { get; set; }
        public Nullable<System.DateTime> entrydate { get; set; }
        public string hours { get; set; }
        public Nullable<int> project_id { get; set; }
        public System.DateTime modified_date { get; set; }
    }
}
