//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlygodknows.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class approval
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> adate { get; set; }
        public Nullable<long> P_id { get; set; }
        public Nullable<long> MPS_id { get; set; }
        public string status { get; set; }
        public Nullable<long> A_id { get; set; }
        public string Susername { get; set; }
        public string Ausername { get; set; }
        public Nullable<long> Empno { get; set; }
    
        public virtual Attendance Attendance { get; set; }
    }
}
