//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlygodknows.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Attendance
    {
        public long ID { get; set; }
        public long EmpID { get; set; }
        [Display(Name = "MTS ID")]
        public long SubMain { get; set; }
        [Display(Name = "1")]
        public string C1 { get; set; }
        [Display(Name = "2")]
        public string C2 { get; set; }
        [Display(Name = "3")]
        public string C3 { get; set; }
        [Display(Name = "4")]
        public string C4 { get; set; }
        [Display(Name = "5")]
        public string C5 { get; set; }
        [Display(Name = "6")]
        public string C6 { get; set; }
        [Display(Name = "7")]
        public string C7 { get; set; }
        [Display(Name = "8")]
        public string C8 { get; set; }
        [Display(Name = "9")]
        public string C9 { get; set; }
        [Display(Name = "10")]
        public string C10 { get; set; }
        [Display(Name = "11")]
        public string C11 { get; set; }
        [Display(Name = "12")]
        public string C12 { get; set; }
        [Display(Name = "13")]
        public string C13 { get; set; }
        [Display(Name = "14")]
        public string C14 { get; set; }
        [Display(Name = "15")]
        public string C15 { get; set; }
        [Display(Name = "16")]
        public string C16 { get; set; }
        [Display(Name = "17")]
        public string C17 { get; set; }
        [Display(Name = "18")]
        public string C18 { get; set; }
        [Display(Name = "19")]
        public string C19 { get; set; }
        [Display(Name = "20")]
        public string C20 { get; set; }
        [Display(Name = "21")]
        public string C21 { get; set; }
        [Display(Name = "22")]
        public string C22 { get; set; }
        [Display(Name = "23")]
        public string C23 { get; set; }
        [Display(Name = "24")]
        public string C24 { get; set; }
        [Display(Name = "25")]
        public string C25 { get; set; }
        [Display(Name = "26")]
        public string C26 { get; set; }
        [Display(Name = "27")]
        public string C27 { get; set; }
        [Display(Name = "28")]
        public string C28 { get; set; }
        [Display(Name = "29")]
        public string C29 { get; set; }
        [Display(Name = "30")]
        public string C30 { get; set; }
        [Display(Name = "31")]
        public string C31 { get; set; }
        public Nullable<long> TotalHours { get; set; }
        public Nullable<long> TotalOverTime { get; set; }
        public Nullable<long> TotalAbsent { get; set; }
        public Nullable<long> AccommodationDeduction { get; set; }
        public Nullable<long> FoodDeduction { get; set; }
        public Nullable<long> TotalWorkingDays { get; set; }
        public Nullable<long> TotalVL { get; set; }
        public Nullable<long> TotalTransefer { get; set; }
        public Nullable<long> TotalSickLeave { get; set; }
        public Nullable<long> FridayHours { get; set; }
        public Nullable<long> Holidays { get; set; }
        public string ManPowerSupply { get; set; }
        public Nullable<long> CompID { get; set; }
        public string Encoded_Absolute_URL { get; set; }
        public string Item_Type { get; set; }
        public string Path { get; set; }
        public string URL_Path { get; set; }
        public string Workflow_Instance_ID { get; set; }
        public string File_Type { get; set; }
        public Nullable<long> xABST { get; set; }
        public Nullable<long> nABST { get; set; }
        public Nullable<long> xOT { get; set; }
        public Nullable<long> nnOT { get; set; }

        public string status { get; set; }
        public virtual LabourMaster LabourMaster { get; set; }
        public virtual MainTimeSheet MainTimeSheet { get; set; }
    }
}
