//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlygodknows.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControlRoom
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> xDate { get; set; }
        public Nullable<int> Room { get; set; }
        public string Remark { get; set; }
        public Nullable<int> EmpID { get; set; }
    }
}
