//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlygodknows.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class LabourMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LabourMaster()
        {
            this.Attendances = new HashSet<Attendance>();
            this.towemps = new HashSet<towemp>();
        }
    
        public long ID { get; set; }
        public long EMPNO { get; set; }
        public int ManPowerSupply { get; set; }
        public string VisaSponser { get; set; }
        [Display(Name = "employee name")]
        public string Person_Name { get; set; }
        public string Position { get; set; }
        public string Nationality { get; set; }
        public Nullable<long> UID_No { get; set; }
        public Nullable<System.DateTime> ResidenceVisaExpiry { get; set; }
        public Nullable<long> LaborCardNumber { get; set; }
        public Nullable<System.DateTime> LaborCardExpiry { get; set; }
        public string PassportNo { get; set; }
        public Nullable<System.DateTime> Passportexpiry { get; set; }
        public string EID { get; set; }
        public Nullable<System.DateTime> EIDExpiry { get; set; }
        public string Status { get; set; }
        public string Photo { get; set; }
        public string Encoded_Absolute_URL { get; set; }
        public Nullable<double> Item_Type { get; set; }
        public string Path { get; set; }
        public string URL_Path { get; set; }
        public string Workflow_Instance_ID { get; set; }
        public string File_Type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendance> Attendances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<towemp> towemps { get; set; }
    }
}
