//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlygodknows.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainShifting
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string For { get; set; }
        public string UsirID { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<double> Ref { get; set; }
        public string Subject { get; set; }
        public string To { get; set; }
        public string Attn { get; set; }
        public string OldREf { get; set; }
        public string Attach { get; set; }
        public bool Ssave { get; set; }
        public Nullable<System.DateTime> SDate { get; set; }
        public Nullable<double> BID { get; set; }
        public string Encoded_Absolute_URL { get; set; }
        public string Item_Type { get; set; }
        public string Path { get; set; }
        public string URL_Path { get; set; }
        public string Workflow_Instance_ID { get; set; }
        public string File_Type { get; set; }
    }
}
