//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlygodknows.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MainTimeSheet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MainTimeSheet()
        {
            this.Attendances = new HashSet<Attendance>();
        }
    
        public long ID { get; set; }

        [DisplayFormat(DataFormatString = "{0:MMMM  yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime TMonth { get; set; }
        public long ManPowerSupplier { get; set; }
        public long Project { get; set; }
        public string Ref { get; set; }
        public Nullable<double> RefNo { get; set; }
        public string UserName { get; set; }
        public string PCName { get; set; }
        public bool SAV { get; set; }
        public string Location { get; set; }
        public string Note { get; set; }
        public bool Startit { get; set; }
        public string Encoded_Absolute_URL { get; set; }
        public string Item_Type { get; set; }
        public string Path { get; set; }
        public string URL_Path { get; set; }
        public string Workflow_Instance_ID { get; set; }
        public string File_Type { get; set; }
        public Nullable<int> TMnth { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendance> Attendances { get; set; }
        public virtual ManPowerSupplier ManPowerSupplier1 { get; set; }
        public virtual ProjectList ProjectList { get; set; }
    }
}
