//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlygodknows.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManPowerSupplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ManPowerSupplier()
        {
            this.MainTimeSheets = new HashSet<MainTimeSheet>();
        }
    
        public long ID { get; set; }
        public string ShortName { get; set; }
        public string Supplier { get; set; }
        public Nullable<double> SkilledRat { get; set; }
        public Nullable<double> NonSkilledRate { get; set; }
        public Nullable<double> NormalTimeUpto { get; set; }
        public Nullable<double> Crtl { get; set; }
        public string Encoded_Absolute_URL { get; set; }
        public string Item_Type { get; set; }
        public string Path { get; set; }
        public string URL_Path { get; set; }
        public string Workflow_Instance_ID { get; set; }
        public string File_Type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MainTimeSheet> MainTimeSheets { get; set; }
    }
}
