//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlygodknows.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manpowerinoutform
    {
        public int Id { get; set; }
        public string camp { get; set; }
        public string companyName { get; set; }
        public long EmpID { get; set; }
        public Nullable<int> mobileNo { get; set; }
        public Nullable<int> roomNo { get; set; }
        public long Project { get; set; }
        public bool SSg { get; set; }
        public bool SSp { get; set; }
        public bool blanket { get; set; }
        public bool bs { get; set; }
        public bool fs { get; set; }
        public bool pillow { get; set; }
        public bool pc { get; set; }
        public bool ck { get; set; }
        public bool rk { get; set; }
        public bool cic { get; set; }
        public bool copon { get; set; }
    
        public virtual LabourMaster LabourMaster { get; set; }
        public virtual ProjectList ProjectList { get; set; }
    }
}
