//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlygodknows.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyCompanyInfo
    {
        public int ID { get; set; }
        public string CompanyNameEng { get; set; }
        public string CompanyNameArab { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string Emirates { get; set; }
        public string POBox { get; set; }
        public string Web { get; set; }
        public string Email { get; set; }
        public byte[] Logo { get; set; }
        public string Data_Location { get; set; }
        public string Application_Title { get; set; }
        public string Application_Icon_Location { get; set; }
        public string FileName { get; set; }
    }
}
