//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlygodknows.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class overtimeref
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public overtimeref()
        {
            this.overtimeemployeelists = new HashSet<overtimeemployeelist>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> overtimedate { get; set; }
        public string overtimeref1 { get; set; }
        public Nullable<long> overtimepro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<overtimeemployeelist> overtimeemployeelists { get; set; }
        public virtual ProjectList ProjectList { get; set; }
    }
}
