//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlygodknows.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PPP
    {
        public string XXX { get; set; }
        public int ID { get; set; }
        public string ZZZ { get; set; }
        public string Field1 { get; set; }
    }
}
