//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlygodknows.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pprint
    {
        public string Name { get; set; }
        public string MainName { get; set; }
        public string Code { get; set; }
        public bool Printt { get; set; }
        public Nullable<double> Balance { get; set; }
        public Nullable<int> Index { get; set; }
    }
}
