//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlygodknows.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShiftingFile
    {
        public int ID { get; set; }
        public int LinkMainShift { get; set; }
        public double Labor { get; set; }
        public Nullable<System.DateTime> EffectDate { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public string Profession { get; set; }
        public string Remarks { get; set; }
        public string Encoded_Absolute_URL { get; set; }
        public string Item_Type { get; set; }
        public string Path { get; set; }
        public string URL_Path { get; set; }
        public string Workflow_Instance_ID { get; set; }
        public string File_Type { get; set; }
        public Nullable<int> Room { get; set; }
    }
}
