//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlygodknows.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Switchboard_Item
    {
        public int SwitchboardID { get; set; }
        public short ItemNumber { get; set; }
        public string ItemText { get; set; }
        public Nullable<short> Command { get; set; }
        public string Argument { get; set; }
        public string ItemText_ara { get; set; }
    }
}
