//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlygodknows.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public int ID { get; set; }
        public string UserID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string UserType { get; set; }
        public string Email { get; set; }
        public string ContactNo { get; set; }
        public string PCSerila { get; set; }
        public string PCModel { get; set; }
        public string Hint { get; set; }
        public Nullable<double> Bransh_Company { get; set; }
        public string Encoded_Absolute_URL { get; set; }
        public string Item_Type { get; set; }
        public string Path { get; set; }
        public string URL_Path { get; set; }
        public string Workflow_Instance_ID { get; set; }
        public string File_Type { get; set; }
        public string AnyDesk_Address { get; set; }
        public string AnyDesk_Password { get; set; }
        public string ShareFolderUser { get; set; }
        public string ShareFolderPassword { get; set; }
        public string RemoteAccessUser { get; set; }
        public string RemoteAccessPassword { get; set; }
        public string ShareFolderPassword2 { get; set; }
    }
}
