//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlygodknows.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trattfile
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string content_type { get; set; }
        public byte[] data { get; set; }
        public Nullable<int> rowref { get; set; }
    
        public virtual towref towref { get; set; }
    }
}
