//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlygodknows.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string About_me { get; set; }
        public string Title { get; set; }
        public string Department { get; set; }
        public string Attachments { get; set; }
        public string Encoded_Absolute_URL { get; set; }
        public string Item_Type { get; set; }
        public string Path { get; set; }
        public string URL_Path { get; set; }
        public string Workflow_Instance_ID { get; set; }
        public string File_Type { get; set; }
    }
}
