//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlygodknows.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class weekendlist
    {
        public int Id { get; set; }
        public string weekend { get; set; }
        public Nullable<long> project_id { get; set; }
    
        public virtual ProjectList ProjectList { get; set; }
    }
}
